### ISSUE TITLE
Build failure on Ubuntu

### ISSUE THREAD

**Issue by rhuppert** [sstephenson/ruby-build#749]
I'm not sure if my problem is related to other issues I've read , but I am experiencing a build failure also.
Installing ruby-2.2.2...

BUILD FAILED (Ubuntu 14.04 using ruby-build 20150413-7-ge9d25d0)

Inspect or clean up the working tree at /tmp/ruby-build.20150422162450.21131
Results logged to /tmp/ruby-build.20150422162450.21131.log
```
Last 10 log lines:
  from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/dependency_installer.rb:373:in `install'
  from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems.rb:558:in `install'
  from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
  from ./tool/rbinstall.rb:721:in `each'
  from ./tool/rbinstall.rb:721:in `block in <main>'
  from ./tool/rbinstall.rb:757:in `call'
  from ./tool/rbinstall.rb:757:in `block in <main>'
  from ./tool/rbinstall.rb:754:in `each'
  from ./tool/rbinstall.rb:754:in `<main>'
```
I was having some odd issues (psych.rb errors) and decided to uninstall all my old versions and install 2.2.2.  2.2.1 also did not install successfully, so I decided to delete .rbenv and start over with no luck.  It may be my issue may be related to my previous problems, but I was hoping for some direction.

I'm running Ubuntu 14.04 and did an apt-update / apt-install for: zlib1g-dev, build-essential, libssl-dev, libreadline-dev, libyaml-dev, libffi-dev and others.

Reading state information... 
autoconf is already the newest version.
bison is already the newest version.
build-essential is already the newest version.
libffi-dev is already the newest version.
libgdbm-dev is already the newest version.
libgdbm3 is already the newest version.
libncurses5-dev is already the newest version.
libreadline6-dev is already the newest version.
zlib1g-dev is already the newest version.
libssl-dev is already the newest version.
libyaml-dev is already the newest version.

More log info:
```
                             bigdecimal 1.2.6
                              io-console 0.4.3
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
/tmp/ruby-build.20150422162450.21131/ruby-2.2.2/.ext/common/psych.rb:370:in `parse': (<unknown>): mapping values are not allowed in this context at line 1 column 9 (Psych::SyntaxError)
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/.ext/common/psych.rb:370:in `parse_stream'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/.ext/common/psych.rb:318:in `parse'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/.ext/common/psych.rb:245:in `load'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/config_file.rb:333:in `load_file'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/config_file.rb:198:in `initialize'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems.rb:297:in `new'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems.rb:297:in `configuration'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/remote_fetcher.rb:51:in `fetcher'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/spec_fetcher.rb:76:in `initialize'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/spec_fetcher.rb:42:in `new'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/spec_fetcher.rb:42:in `fetcher'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/resolver/installer_set.rb:37:in `initialize'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/dependency_installer.rb:430:in `new'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/dependency_installer.rb:430:in `resolve_dependencies'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems/dependency_installer.rb:373:in `install'
	from /tmp/ruby-build.20150422162450.21131/ruby-2.2.2/lib/rubygems.rb:558:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-all] Error 1
'''

**Comment by rhuppert** [comment]
Somehow a spurious character was entered into the .gemrc file which created all the havoc.
