### ISSUE TITLE
Can't install rbx-2.5.3 on Mavericks (LLVM issue)

### ISSUE THREAD

**Issue by quinn** [sstephenson/ruby-build#762]
After reading about this issue in various places, I arrived at this command (after brew installing llvm):

```
$ CC=clang CONFIGURE_OPTS="--llvm-config /usr/local/opt/llvm/bin/llvm-config" rbenv install rbx-2.5.3
```

fails with this output:

```
Downloading rubinius-2.5.3.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/9af4d6e9d1e78a586579c86b9eb9a082cb863885d4a7cf33989d73280461e5fc
Installing rubinius-2.5.3...

BUILD FAILED (OS X 10.9.5 using ruby-build 20150506)

Inspect or clean up the working tree at /var/folders/4c/fwhfl1v11c74zyvbfljk_t5c0000gq/T/ruby-build.20150519102653.73172
Results logged to /var/folders/4c/fwhfl1v11c74zyvbfljk_t5c0000gq/T/ruby-build.20150519102653.73172.log

Last 10 log lines:
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

LLVM version:

```
$ /usr/local/opt/llvm/bin/llvm-config --version
3.6.0
```

**Comment by quinn** [comment]
also:

```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
```

**Comment by mislav** [comment]
It's always a good idea to try with latest Rubinius version first, since they're constantly improving the build process. Please upgrade ruby-build to latest version and try `rbx-2.5.5`, thanks

**Comment by quinn** [comment]
cool, thank you. Still getting the same problem though. I tried it also with no env set. 

```
$ CC=clang CONFIGURE_OPTS="--llvm-config /usr/local/opt/llvm/bin/llvm-config" rbenv install rbx-2.5.5
Downloading rubinius-2.5.5.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/217659849ca2c67322d24ce7167e760dc835f32a701ca6e558703914ca82d02f
Installing rubinius-2.5.5...

BUILD FAILED (OS X 10.9.5 using ruby-build 20150519)

Inspect or clean up the working tree at /var/folders/4c/fwhfl1v11c74zyvbfljk_t5c0000gq/T/ruby-build.20150519135025.74735
Results logged to /var/folders/4c/fwhfl1v11c74zyvbfljk_t5c0000gq/T/ruby-build.20150519135025.74735.log

Last 10 log lines:
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
	from /Users/lsu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM
```

**Comment by mislav** [comment]
Are you certain that `/usr/local/opt/llvm/bin/llvm-config` is compatible with this version of Rubinius?

Also what is the full failed stack trace (available from the log file)?

**Comment by sferik** [comment]
I don’t think the latest Rubinius works with the latest LLVM. See https://twitter.com/rubinius/status/598569219622576128.

**Comment by quinn** [comment]
@sferik thanks for the info. I tried again with different versions of LLVM with the same effect. Maybe I'm not using CONFIGURE_OPTS properly? e.g:

this fails:
```
$ CONFIGURE_OPTS="--llvm-config /Users/lsu/src/rubinius-2.2.10/vendor/llvm/Release/bin/llvm-config" rbenv install rbx-2.5.5
```

version:
```
$ /Users/lsu/src/rubinius-2.2.10/vendor/llvm/Release/bin/llvm-config --version
3.2svn
```

Also, when I originally tried this I had 3.5.1 one installed, not 3.6.0.

**Comment by quinn** [comment]
I also tried with `CONFIGURE_OPTS="--ignore-system"`as described in the Rubinius docs.

configure.log
```
[2015-05-19 17:31:48] Configuring Rubinius...
[2015-05-19 17:31:48] Command line: "--prefix=/Users/lsu/.rbenv/versions/rbx-2.5.5"
[2015-05-19 17:31:48] Checking clang:
[2015-05-19 17:31:48]  found
[2015-05-19 17:31:48] Checking clang++:
[2015-05-19 17:31:48]  found
[2015-05-19 17:31:48] ---

Detected old configuration settings, forcing a clean build
---
[2015-05-19 17:31:48]   Checking for 'llvm-config':
[2015-05-19 17:31:48] not found
[2015-05-19 17:31:48]*** ERROR ABORT: unable to set up LLVM
```

i'm gonna try to add llvm-config to my $PATH and see if that makes any difference....

**Comment by quinn** [comment]
@sferik @mislav I was able to (with some difficulty) compile and install rbx from their repository into rbenv.

**Comment by kwugirl** [comment]
Leaving a comment here in case it helps someone in the future, between this issue and https://github.com/sstephenson/ruby-build/issues/796, this is what I believe ultimately worked for me to install Rubinius on Mavericks:

```
brew install llvm35
CC=clang RUBY_CONFIGURE_OPTS="--llvm-config /usr/local/opt/llvm35/bin/llvm-config-3.5" rbenv install rbx-2.5.8
```

So you need LLVM < 3.6 as well as to specify the path to that config with RUBY_CONFIGURE_OPTS.

**Comment by ur0** [comment]
Sorry if I'm necro-bumping but here's what I did (just in case it might help someone).
`sudo ln -s /usr/bin/llvm-config-3.5 /usr/bin/llvm-config`.
I know that this isn't the cleanest way, but ruby-build wasn't giving a damn to my `RUBY_CONFIGURE_OPTS`.
