### ISSUE TITLE
Can't compile ruby 2.2.3: stack level too deep

### ISSUE THREAD

**Issue by brauliobo** [sstephenson/ruby-build#802]
```
~/P/n/master git:master ❯❯❯ rbenv install 2.2.3
Installing ruby-2.2.3...

BUILD FAILED (Arch rolling using ruby-build 20150818)

Inspect or clean up the working tree at /tmp/braulio/ruby-build.20150821083006.28850
Results logged to /tmp/braulio/ruby-build.20150821083006.28850.log

Last 10 log lines:
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
./tool/rbinstall.rb:728:in `block in <main>': stack level too deep (SystemStackError)
        from ./tool/rbinstall.rb:757:in `call'
        from ./tool/rbinstall.rb:757:in `block in <main>'
        from ./tool/rbinstall.rb:754:in `each'
        from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:246: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```

**Comment by mislav** [comment]
Ouch! I haven't seen this before. Maybe it's a Ruby build bug with Arch linux? /cc @hsbt

**Comment by brauliobo** [comment]
the full log:
```
config.status: creating x86_64-linux-fake.rb
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --install=all --rdoc-output=".ext/rdoc"
installing binary commands:   /home/braulio/.rbenv/versions/2.2.3/bin
installing base libraries:    /home/braulio/.rbenv/versions/2.2.3/lib
installing arch files:        /home/braulio/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-linux
installing pkgconfig data:    /home/braulio/.rbenv/versions/2.2.3/lib/pkgconfig
installing command scripts:   /home/braulio/.rbenv/versions/2.2.3/bin
installing library scripts:   /home/braulio/.rbenv/versions/2.2.3/lib/ruby/2.2.0
installing common headers:    /home/braulio/.rbenv/versions/2.2.3/include/ruby-2.2.0
installing manpages:          /home/braulio/.rbenv/versions/2.2.3/share/man/man1
installing extension objects: /home/braulio/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-linux
installing extension objects: /home/braulio/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/x86_64-linux
installing extension objects: /home/braulio/.rbenv/versions/2.2.3/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
installing extension headers: /home/braulio/.rbenv/versions/2.2.3/include/ruby-2.2.0/x86_64-linux
installing extension scripts: /home/braulio/.rbenv/versions/2.2.3/lib/ruby/2.2.0
installing extension scripts: /home/braulio/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0
installing extension scripts: /home/braulio/.rbenv/versions/2.2.3/lib/ruby/vendor_ruby/2.2.0
installing extension headers: /home/braulio/.rbenv/versions/2.2.3/include/ruby-2.2.0/ruby
installing default gems:      /home/braulio/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.2.6
                              io-console 0.4.3
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /home/braulio/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              minitest-5.4.3.gem
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
./tool/rbinstall.rb:728:in `block in <main>': stack level too deep (SystemStackError)
        from ./tool/rbinstall.rb:757:in `call'
        from ./tool/rbinstall.rb:757:in `block in <main>'
        from ./tool/rbinstall.rb:754:in `each'
        from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:246: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```

**Comment by brauliobo** [comment]
archlinux uses gcc 5.2, maybe it is because of that..

**Comment by hsbt** [comment]
I can't reproduce it.

```
[hsbt@chkbuild006 ~]$ rbenv install 2.2.3
Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...
Installed ruby-2.2.3 to /home/hsbt/.rbenv/versions/2.2.3
[hsbt@chkbuild006 ~]$ gcc -v
Using built-in specs.
(snip)
Thread model: posix
gcc version 5.2.0 (GCC)
[hsbt@chkbuild006 ~]$ uname -a
Linux chkbuild006.hsbt.org 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux
```

**Comment by brauliobo** [comment]
just worked here... maybe another ruby from system was used before, now I have switched to ruby 2.2.2 from rbenv before `rbenv install`.

thanks!
